CsvImport: don't use "not", "or", "and" keywords
These aren't accepted by MSVC, and cause it to ICE for x86 and ARM64
builds:

    [...]\CsvImportWidget.cpp(218): error C2065: 'not': undeclared identifier
    [...]\CsvImportWidget.cpp(218): error C2146: syntax error: missing ')' before identifier 'm_parserModel'
    [...]\CsvImportWidget.cpp(218): error C2059: syntax error: ')'
    [...]\CsvImportWidget.cpp(219): error C2143: syntax error: missing ';' before 'continue'
    [...]\CsvImportWidget.cpp(265): error C2065: 'not': undeclared identifier
    [...]\CsvImportWidget.cpp(265): error C2146: syntax error: missing ')' before identifier 'm_parserModel'
    [...]\CsvImportWidget.cpp(265): error C2059: syntax error: ')'
    [...]\CsvImportWidget.cpp(266): error C2143: syntax error: missing ';' before 'continue'
    [...]\CsvImportWidget.cpp(273): error C2065: 'not': undeclared identifier
    [...]\CsvImportWidget.cpp(273): error C2146: syntax error: missing ')' before identifier 'groupList'
    [...]\CsvImportWidget.cpp(273): error C2059: syntax error: ')'
    [...]\CsvImportWidget.cpp(274): error C2146: syntax error: missing ';' before identifier 'is_root'
    [...]\CsvImportWidget.cpp(275): error C2181: illegal else without matching if
    [...]\CsvImportWidget.cpp(275): error C2065: 'not': undeclared identifier
    [...]\CsvImportWidget.cpp(275): error C2146: syntax error: missing ')' before identifier 'groupLabel'
    [...]\CsvImportWidget.cpp(275): error C2059: syntax error: ')'
    [...]\CsvImportWidget.cpp(276): error C2146: syntax error: missing ';' before identifier 'is_empty'
    [...]\CsvImportWidget.cpp(277): error C2181: illegal else without matching if
    [...]\CsvImportWidget.cpp(283): error C2146: syntax error: missing ')' before identifier 'and'
    [...]\CsvImportWidget.cpp(285): error C2181: illegal else without matching if
    [...]\CsvImportWidget.cpp(283): fatal error C1903: unable to recover from previous error(s); stopping compilation
    Internal Compiler Error in C:\PROGRA~3\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1413~1.261\bin\Hostx86\arm64\cl.exe.  You will be prompted to send an error report to Microsoft later.
    INTERNAL COMPILER ERROR in 'C:\PROGRA~3\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1413~1.261\bin\Hostx86\arm64\cl.exe'
	Please choose the Technical Support command on the Visual C++
	Help menu, or open the Technical Support help file for more information
    [51/87] Building CXX object src\CMakeFiles\keepassx_core.dir\gui\entry\EditEntryWidget.cpp.obj
    ninja: build stopped: subcommand failed.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>